# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
