# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20160426_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AddField(
            model_name='match',
            name='items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
