# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20160426_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='available',
            new_name='finished',
        ),
    ]
