# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20160426_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='delta',
            field=models.FloatField(default=0),
        ),
    ]
