# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_team_delta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='team',
            name='howfarback',
            field=models.IntegerField(default=999999),
        ),
        migrations.AddField(
            model_name='team',
            name='lastgames',
            field=models.IntegerField(default=0),
        ),
    ]
