# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20160427_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lastgames',
            field=models.IntegerField(default=999999),
        ),
    ]
