# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20160427_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('howfarback', models.IntegerField(default=999999)),
                ('lastgames', models.IntegerField(default=999999)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='howfarback',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lastgames',
        ),
    ]
