# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_delete_teamset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('delta', models.FloatField(default=0)),
                ('winrate', models.FloatField(default=0)),
                ('odds', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('howfarback', models.IntegerField(default=99999)),
                ('lastgames', models.IntegerField(default=99999)),
            ],
            options={
                'verbose_name_plural': 'Team Stat Sets',
                'verbose_name': 'Team Stat Set',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='team',
            name='games',
        ),
        migrations.RemoveField(
            model_name='team',
            name='odds',
        ),
        migrations.RemoveField(
            model_name='team',
            name='winrate',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AddField(
            model_name='teamstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Team'),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='teamstatset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.TeamStatSet'),
        ),
    ]
