# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20160427_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamStatSet',
            new_name='StatSet',
        ),
        migrations.RemoveField(
            model_name='teamstat',
            name='teamstatset',
        ),
        migrations.AddField(
            model_name='teamstat',
            name='statset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scraper.StatSet'),
            preserve_default=False,
        ),
    ]
