# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_auto_20160427_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='counted',
            field=models.BooleanField(default=True),
        ),
    ]
