# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_match_counted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='counted',
            new_name='valid',
        ),
    ]
