# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_statset_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='items',
        ),
        migrations.RemoveField(
            model_name='match',
            name='people',
        ),
    ]
