# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_remove_statset_howfarback'),
    ]

    operations = [
        migrations.AddField(
            model_name='statset',
            name='delta_days',
            field=models.IntegerField(default=60),
        ),
    ]
