# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_statset_delta_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='statset',
            name='delta_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
